package com.xl.deploy.gui;

import com.xl.deploy.entity.DeploymentEntity;
import com.xl.deploy.service.DeploymentPackageService;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.*;
import java.util.Properties;
import javax.swing.*;
import lombok.extern.log4j.Log4j;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * Created with 徐立.生成部署目录
 *
 * @author 徐立
 * @version 1.0 2019-04-12 17:17
 * To change this template use File | Settings | File Templates.
 * @date 2019-04-12
 * @time 17:17
 */
@Log4j
public class DeployForm extends JFrame {
    private static final String AUTHOR = "author";
    private static volatile String author = "徐立";
    private static String propertyFileName = "deploy.properties";
    static {
        File propertFile = new File(propertyFileName);
        if (propertFile.exists()) {
            try (FileInputStream is = new FileInputStream(propertFile)) {
                Properties properties = new Properties();
                properties.load(is);
                author = properties.getProperty(AUTHOR);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
    @Autowired
    private DeploymentPackageService service;
    private JPanel contentPane;
    private JButton buttonCancel;
    private JButton demandReleasePackageBtn;
    private JButton BUGDelpoyButton;
    private JTextArea code;
    private JTextArea textArea2;
    private JScrollPane codePanel;
    private JTextField taskNameTx;
    private JTextField authorField;
    private boolean writeAuthor = false;
    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }
    public DeployForm() {
        init();
    }
    
    private void init() {
        this.setVisible(true);
        setTitle("有建议发送给徐立78645574@qq.com");
        //设置作者
        authorField.setText(author);
        setContentPane(contentPane);
        //不能改变大小
        this.setResizable(false);
        getRootPane().setDefaultButton(demandReleasePackageBtn);
        buttonCancel.addActionListener(e -> onCancel());
        addBtnEvent(demandReleasePackageBtn, true);
        addBtnEvent(BUGDelpoyButton, false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });
    }
    
    /**
     * 退出调用的方法
     */
    private void onCancel() {
        if (writeAuthor) {
            File propertFile = new File(propertyFileName);
            try {
                Properties prop = new Properties();
                prop.setProperty(AUTHOR, authorField.getText());
                FileOutputStream fileOutputStream = new FileOutputStream(propertFile, false);//true表示追加打开
                prop.store(fileOutputStream, "作者");
            } catch (FileNotFoundException e) {
                log.error(e);
            } catch (IOException e) {
            }
        }
        dispose();
        //这个会关闭窗口,但是自定义关闭按钮不会终止程序
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        //这个会关闭程序
        System.exit(0);
    }
    
    /**
     * 按钮添加实际
     *
     * @param button
     * @param b true：任务，false：BUG
     */
    private void addBtnEvent(JButton button, boolean b) {
        button.addActionListener(e -> {
            try {
                button.setEnabled(false);
                String authorText = authorField.getText();
                if (!StringUtils.equals(author, authorText)) {
                    writeAuthor = true;
                }
                //看作者是否变更，如果作者变更的话则保持
                DeploymentEntity entity = new DeploymentEntity(authorText, b, code.getText(),
                                                               taskNameTx.getText());
                service.createFile(entity);
            } catch (IOException e1) {
                e1.printStackTrace();
            } finally {
                button.setEnabled(true);
            }
        });
    }
    
    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                 |
                                                                                 com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                 null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                             com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                             com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                             com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                             1, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1,
                                                                            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                            com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                            |
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                            |
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                            null, null, null, 0, false));
        buttonCancel = new JButton();
        buttonCancel.setText("关闭");
        panel2.add(buttonCancel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                                  com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                  com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                  |
                                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                  null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel3, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                 |
                                                                                 com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                 null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        panel3.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1,
                                                                             com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                             com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL,
                                                                             1,
                                                                             com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                             null, null, null, 0, false));
        codePanel = new JScrollPane();
        panel3.add(codePanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1,
                                                                               com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                               com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                               |
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                               |
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                               null, new Dimension(500, 500), null, 0, false));
        code = new JTextArea();
        code.setToolTipText("code.txt");
        codePanel.setViewportView(code);
        textArea2 = new JTextArea();
        textArea2.setToolTipText("发布文档中的内容");
        BUGDelpoyButton = new JButton();
        BUGDelpoyButton.setText("BUG部署包");
        panel3.add(BUGDelpoyButton, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1,
                                                                                     com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                     com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                     com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                     |
                                                                                     com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                     com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                     null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel3.add(panel4, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
                                                                            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                            com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                            1,
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                            null, null, null, 0, false));
        taskNameTx = new JTextField();
        taskNameTx.setText("");
        taskNameTx.setToolTipText("任务名称");
        panel4.add(taskNameTx, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                                com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                null, new Dimension(150, -1), null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel3.add(panel5, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1,
                                                                            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                            com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                            |
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                            |
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                            null, null, null, 0, false));
        authorField = new JTextField();
        authorField.setText("徐立");
        authorField.setToolTipText("作者");
        panel5.add(authorField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                 null, new Dimension(150, -1), null, 0, false));
        demandReleasePackageBtn = new JButton();
        demandReleasePackageBtn.setText("任务部署包");
        panel3.add(demandReleasePackageBtn, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2,
                                                                                             com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                             com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                             com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                             |
                                                                                             com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                             com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                             null, null, null, 0, false));
    }
    
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
